CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    id       UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(), 
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);